Dataset:
  subj: 1
  batch_size: 256
  data_type: train
  brain_type: left
  data_dir: /content
  csv_file_path: /content/Text_Data
  model_save_folder: /content/drive/MyDrive/MRI/Result
  train_type: image

MLP_model:
  channels: 32
  patch_size: 4
  dim: 2048
  depth: 4

parameter:
  epoch: 15
  lr: 0.0005