Dataset:
  subj: 1
  batch_size: 128
  data_type: train
  brain_type: left
  data_dir: /content
  csv_file_path: /content/Text_Data
  model_save_folder: ./Model_Save
  train_type: image

MLP_model:
  channels: 56
  patch_size: 4
  dim: 2048
  depth: 2

parameter:
  epoch: 20
  lr: 0.001